fix: make workflow abort if minecraft server could not start

diff --git a/.github/workflows/extract-configs.yml b/.github/workflows/extract-configs.yml
--- a/.github/workflows/extract-configs.yml
+++ b/.github/workflows/extract-configs.yml
@@ -31,9 +31,13 @@ jobs:
             
       - name: Wait for container to become healthy
         run: |
-            while [[ "$(docker inspect -f '{{.State.Health.Status}}' minecraft-server)" != "healthy" ]]; do
-              sleep 5
-            done    
+              while [[ "$(docker inspect -f '{{.State.Health.Status}}' minecraft-server)" != "healthy" ]]; do
+                if [[ "$(docker inspect -f '{{.State.Status}}' minecraft-server)" == "exited" ]]; then
+                  echo "Container has stopped. Aborting workflow."
+                  exit 1
+                fi
+                sleep 5
+              done
 
       - name: Stop Minecraft Server
         run: docker stop minecraft-server
